# Generated by Django 4.1.7 on 2023-04-03 10:06

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=220, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Number')),
                ('user_type', models.CharField(choices=[('member', 'Member'), ('business', 'Business'), ('ngo', 'NGO'), ('news_agency', 'News Agency')], default='member', max_length=20)),
                ('firstname', models.CharField(blank=True, max_length=40, null=True)),
                ('lastname', models.CharField(blank=True, max_length=40, null=True)),
                ('language', models.CharField(blank=True, choices=[('english', 'English'), ('arabic', 'Arabic')], max_length=20, null=True, verbose_name='Language')),
                ('currency', models.CharField(blank=True, choices=[('inr', 'INR'), ('dinar', 'Dinar')], max_length=10, null=True, verbose_name='Currency')),
                ('image', models.ImageField(blank=True, null=True, upload_to=account.models.profile_pic_path, verbose_name='Profile Pic')),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to=account.models.profile_cover_pic_path, verbose_name='Cover Picture')),
                ('paid_account', models.BooleanField(default=False, verbose_name='Paid Account')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('administrator_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Administrator Name')),
                ('business_category', models.CharField(choices=[('cat1', 'Cat1')], default='cat1', max_length=100, verbose_name='Business Category')),
                ('business_contact', models.CharField(blank=True, max_length=11, null=True, verbose_name='Business Contact')),
                ('business_email', models.EmailField(blank=True, max_length=220, null=True, verbose_name='Business Email')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Website Url')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('menu', models.FileField(blank=True, null=True, upload_to='', verbose_name='Menu')),
                ('newsletter_subscribed', models.BooleanField(default=False, verbose_name='Newsletter Subscribed')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favourite', models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NgoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Video Title')),
                ('link', models.URLField(verbose_name='Video Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('users_liked', models.ManyToManyField(related_name='users_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('location', models.TextField(blank=True, null=True, verbose_name='Property Location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=30, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='Country')),
                ('zipcode', models.IntegerField(blank=True, null=True, verbose_name='Zipcode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Full Name')),
                ('relation', models.CharField(choices=[('wife', 'Wife'), ('husband', 'Husband'), ('daughter', 'Daughter'), ('son', 'Son'), ('mother', 'Mother'), ('father', 'Father')], max_length=10, verbose_name='Relation')),
                ('image', models.ImageField(upload_to=account.models.family_member_pic, verbose_name='Member Pic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_partners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(max_length=6)),
                ('usage', models.CharField(choices=[('Register', 'Register'), ('Forgot', 'Forgot')], default='Register', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
