# Generated by Django 4.1.7 on 2023-04-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_myuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('member', 'Member'), ('business', 'Business'), ('ngo', 'NGO'), ('news_agency', 'News Agency')], default='member', max_length=20),
        ),
    ]
