# Generated by Django 4.1.7 on 2023-04-03 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_myuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='newsletter_subscribed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Newsletter Subscribed'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='paid_account',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Paid Account'),
        ),
    ]
