# Generated by Django 4.1.7 on 2023-04-03 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_myuser_favourite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='newsletter_subscribed',
            field=models.BooleanField(default=False, verbose_name='Newsletter Subscribed'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='paid_account',
            field=models.BooleanField(default=False, verbose_name='Paid Account'),
        ),
    ]
