# Generated by Django 4.1.7 on 2023-04-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_myuser_favourite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('member', 'Member'), ('business', 'Business'), ('ngo', 'NGO'), ('news_agency', 'News Agency')], max_length=20),
        ),
    ]
