# Generated by Django 4.1.7 on 2023-04-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_myuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='currency',
            field=models.CharField(choices=[('inr', 'INR'), ('usd', 'Dollar'), ('dinar', 'Dinar')], default='usd', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('arabic', 'Arabic')], default='en', max_length=20, verbose_name='Language'),
        ),
    ]
