# Generated by Django 4.1.7 on 2023-04-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_myuser_currency_alter_myuser_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('numcode', models.SmallIntegerField()),
                ('nicename', models.CharField(max_length=80)),
                ('iso', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
                ('phonecode', models.SmallIntegerField()),
            ],
        ),
    ]
