# Generated by Django 4.1.7 on 2023-04-04 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.country'),
        ),
    ]
