# Generated by Django 4.1.7 on 2023-04-04 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_myuser_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('member', 'Member'), ('business', 'Business'), ('ngo', 'NGO'), ('news_agency', 'News Agency')], max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='currency',
            field=models.CharField(choices=[('usd', 'Dollar'), ('eur', 'Euro'), ('gbp', 'British Pound'), ('ils', 'Israeli Shekels,'), ('aud', 'Australian Dollar')], default='usd', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('he', 'Hebrew'), ('ru', 'Russian'), ('de', 'German'), ('pt', 'Portuguese'), ('ar', 'Arabic')], default='en', max_length=20, verbose_name='Language'),
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.plan')),
            ],
        ),
    ]
