# Generated by Django 4.1.7 on 2023-04-04 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_plan_alter_myuser_currency_alter_myuser_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
