# Generated by Django 4.1.7 on 2023-04-05 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_planfeature_numbers_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.plan'),
        ),
    ]
