# Generated by Django 4.1.7 on 2023-04-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_temptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='donation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='platform',
            field=models.FloatField(default=0),
        ),
    ]
