# Generated by Django 4.1.7 on 2023-04-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_location_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zipcode',
            field=models.IntegerField(verbose_name='Zipcode'),
        ),
    ]
