# Generated by Django 4.1.7 on 2023-04-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_location_city_alter_location_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(default='', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Property Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
