# Generated by Django 4.1.7 on 2023-04-08 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_location_latitude_alter_location_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='menu',
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.FileField(upload_to='', verbose_name='Menu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
