# Generated by Django 4.1.7 on 2023-04-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_remove_myuser_menu_restaurantmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='business_category',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('real_estate', 'Real Estate')], default='cat1', max_length=100, verbose_name='Business Category'),
        ),
    ]
