# Generated by Django 4.1.7 on 2023-04-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_remove_deliverypartner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='delivery_partner',
            field=models.ManyToManyField(blank=True, default=None, to='account.deliverypartner'),
        ),
    ]
