# Generated by Django 4.1.7 on 2023-04-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_businesscategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='business_category',
        ),
    ]
