# Generated by Django 4.1.7 on 2023-04-10 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_remove_myuser_business_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='business_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.businesscategory', verbose_name='Business Category'),
        ),
    ]
