# Generated by Django 4.1.7 on 2023-04-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_alter_myuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngovideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
