# Generated by Django 4.1.7 on 2023-04-11 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_alter_ngovideo_users_liked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NgoVideo',
        ),
    ]
