# Generated by Django 4.1.7 on 2023-04-11 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_ngovideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscategory',
            name='image',
        ),
    ]
