# Generated by Django 4.1.7 on 2023-04-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_businesscategory_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='usage',
            field=models.CharField(choices=[('Register', 'Register'), ('Forgot', 'Forgot'), ('Change Email', 'Change Email')], default='Register', max_length=20),
        ),
    ]
