# Generated by Django 4.1.7 on 2023-04-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_alter_code_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('iso_code', models.CharField(max_length=3)),
            ],
        ),
    ]
