# Generated by Django 4.1.7 on 2023-04-12 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_currencyexchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
