# Generated by Django 4.1.7 on 2023-04-12 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_alter_myuser_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgoReferalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referal_token', models.CharField(default=uuid.uuid4, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_referal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
