# Generated by Django 4.1.7 on 2023-04-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscategory',
            name='parent',
        ),
    ]
