# Generated by Django 4.1.7 on 2023-04-19 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_remove_businesscategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='favourite',
        ),
        migrations.AddField(
            model_name='myuser',
            name='favourite_user',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
