# Generated by Django 4.1.7 on 2023-04-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0017_review'),
        ('account', '0051_remove_myuser_favourite_myuser_favourite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='favourite_deal',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite_deals', to='deals.deal'),
        ),
    ]
