# Generated by Django 4.1.7 on 2023-04-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0004_alter_classified_contact_phone'),
        ('account', '0052_myuser_favourite_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='favourite_classified',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite_classifieds', to='classifieds.classified'),
        ),
    ]
