# Generated by Django 4.1.7 on 2023-04-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_myuser_favourite_classified'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='favourite_ngo_videos',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite_ngo_videos', to='account.ngovideo'),
        ),
    ]
