# Generated by Django 4.1.7 on 2023-04-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_myuser_favourite_ngo_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='favourite_ngo_videos',
            new_name='favourite_ngo_video',
        ),
    ]
