# Generated by Django 4.1.7 on 2023-04-20 04:58

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_rename_favourite_ngo_videos_myuser_favourite_ngo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='default_images/default_profile_pic.jpeg', upload_to=account.models.profile_pic_path, verbose_name='Profile Pic'),
        ),
    ]
