# Generated by Django 4.1.7 on 2023-04-20 04:59

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cover_pic',
            field=models.ImageField(default='default_images/default_cover_pic.png', upload_to=account.models.profile_cover_pic_path, verbose_name='Cover Picture'),
        ),
    ]
