# Generated by Django 4.1.7 on 2023-05-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_alter_myuser_cover_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='email_add',
            field=models.EmailField(blank=True, default='', max_length=220, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='phone_num',
            field=models.CharField(blank=True, default='', max_length=17, verbose_name='Phone Number'),
        ),
    ]
