# Generated by Django 4.1.7 on 2023-05-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0058_familymember_email_add_familymember_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='email_add',
            field=models.EmailField(max_length=220, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='phone_num',
            field=models.CharField(max_length=17, verbose_name='Phone Number'),
        ),
    ]
