# Generated by Django 4.1.7 on 2023-05-14 05:16

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_alter_familymember_email_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='image',
            field=models.ImageField(null=True, upload_to=account.models.family_member_pic, verbose_name='Member Pic'),
        ),
    ]
