# Generated by Django 4.1.7 on 2023-05-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0011_alter_classifiedimage_classified'),
        ('account', '0060_alter_familymember_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='pinned_classified',
            field=models.ManyToManyField(blank=True, default=None, related_name='pinned_classifieds', to='classifieds.classified'),
        ),
    ]
