# Generated by Django 4.1.7 on 2023-05-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_myuser_pinned_classified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='currency',
            field=models.CharField(choices=[('usd', 'Dollar'), ('eur', 'Euro'), ('gbp', 'British Pound'), ('ils', 'Israeli Shekels'), ('aud', 'Australian Dollar')], default='usd', max_length=10, verbose_name='Currency'),
        ),
    ]
