# Generated by Django 4.1.7 on 2023-05-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_alter_myuser_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
