# Generated by Django 4.1.7 on 2023-05-23 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_alter_deliverypartner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ngos_associated', to=settings.AUTH_USER_MODEL),
        ),
    ]
