# Generated by Django 4.1.7 on 2023-05-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_job_job_type'),
        ('account', '0065_alter_myuser_ngo'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='favourite_job',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite_jobs', to='jobs.job'),
        ),
    ]
