# Generated by Django 4.1.7 on 2023-06-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_myuser_favourite_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='from_currency',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='to_currency',
            field=models.CharField(max_length=24),
        ),
    ]
