# Generated by Django 4.1.7 on 2023-06-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0067_alter_currencyexchangerate_from_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='currency',
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='from_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frm_cur', to='account.currency'),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='to_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_cur', to='account.currency'),
        ),
    ]
