# Generated by Django 4.1.7 on 2023-06-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0070_alter_myuser_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='currency',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_currency', to='account.currency'),
        ),
    ]
