# Generated by Django 4.1.7 on 2023-06-23 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0072_myuser_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='stripe_customer_id',
        ),
        migrations.CreateModel(
            name='StripeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100, null=True)),
                ('source_token', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
