# Generated by Django 4.1.7 on 2023-06-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0073_remove_myuser_stripe_customer_id_stripedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='stripe_customer_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='stripe_source_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='StripeDetail',
        ),
    ]
