# Generated by Django 4.1.7 on 2023-06-27 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0074_myuser_stripe_customer_id_myuser_stripe_source_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='stripe_source_token',
        ),
        migrations.CreateModel(
            name='StripeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=200)),
                ('payment_method', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
