# Generated by Django 4.1.7 on 2023-06-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0075_remove_myuser_stripe_source_token_stripedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripedetail',
            name='payment_method',
            field=models.TextField(null=True),
        ),
    ]
