# Generated by Django 4.1.7 on 2023-06-28 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0077_stripedetail_amount_stripedetail_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripedetail',
            name='cancellation_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stripedetail',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stripedetail',
            name='plan_to_activate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.plan'),
        ),
        migrations.AddField(
            model_name='stripedetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('Cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
