# Generated by Django 4.1.7 on 2023-06-29 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0079_alter_stripedetail_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_gateway', models.CharField(choices=[('stripe', 'Stripe'), ('tranzila', 'Tranzila')], default='stripe', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stripe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.stripedetail')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
