# Generated by Django 4.1.7 on 2023-06-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0081_stripedetail_client_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripedetail',
            name='client_secret',
        ),
        migrations.AddField(
            model_name='planfeature',
            name='feature_type',
            field=models.CharField(choices=[('deal', 'Deal'), ('classified', 'Classified'), ('news', 'News'), ('job', 'Job')], default='deal', max_length=12),
        ),
    ]
