# Generated by Django 4.1.7 on 2023-06-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0083_alter_planfeature_feature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeature',
            name='feature_type',
            field=models.CharField(choices=[('deal', 'Deal'), ('classified', 'Classified'), ('news', 'News'), ('job', 'Job'), ('location', 'Location')], default='deal', max_length=20),
        ),
    ]
