# Generated by Django 4.1.7 on 2023-06-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0084_alter_planfeature_feature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='extra_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stripedetail',
            name='item_type',
            field=models.CharField(choices=[('plan', 'Plan'), ('deal', 'Deal')], default='plan', max_length=20),
        ),
    ]
