# Generated by Django 4.1.7 on 2023-07-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0085_myuser_extra_deal_alter_stripedetail_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='extra_location',
            field=models.IntegerField(default=0),
        ),
    ]
