# Generated by Django 4.1.7 on 2023-07-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0086_myuser_extra_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripedetail',
            name='locations_to_activate',
            field=models.IntegerField(default=0),
        ),
    ]
