# Generated by Django 4.1.7 on 2023-07-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0087_stripedetail_locations_to_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='extra_classified',
            field=models.BooleanField(default=False),
        ),
    ]
