# Generated by Django 4.1.7 on 2023-07-07 06:08

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0089_alter_location_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='image',
            field=models.ImageField(default='default_images/default_profile_pic.jpeg', upload_to=account.models.family_member_pic, verbose_name='Member Pic'),
        ),
    ]
