# Generated by Django 4.1.7 on 2023-07-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0091_currency_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='sign',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
