# Generated by Django 4.1.7 on 2023-07-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0094_myuser_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
