# Generated by Django 4.1.7 on 2023-07-21 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0095_alter_myuser_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_approved',
        ),
    ]
