# Generated by Django 4.1.7 on 2023-07-25 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0097_myuser_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_member_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
