# Generated by Django 4.1.7 on 2023-07-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0098_myuser_is_deleted_myuser_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='relation',
            field=models.CharField(choices=[('friend', 'Friend'), ('husband', 'Family')], max_length=10, null=True, verbose_name='Relation'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('friend', 'Friend'), ('husband', 'Family')], max_length=10, verbose_name='Relation'),
        ),
    ]
