# Generated by Django 4.1.7 on 2023-07-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0099_myuser_relation_alter_familymember_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('friend', 'Friend'), ('family', 'Family')], max_length=10, verbose_name='Relation'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='relation',
            field=models.CharField(choices=[('friend', 'Friend'), ('family', 'Family')], max_length=10, null=True, verbose_name='Relation'),
        ),
    ]
