# Generated by Django 4.1.7 on 2023-07-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0101_activitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='created_tile',
            new_name='created_time',
        ),
    ]
