# Generated by Django 4.1.7 on 2023-08-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0102_rename_created_tile_activitylog_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('friend', 'Friends'), ('family', 'Family')], max_length=10, verbose_name='Relation'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='relation',
            field=models.CharField(choices=[('friend', 'Friends'), ('family', 'Family')], max_length=10, null=True, verbose_name='Relation'),
        ),
    ]
