# Generated by Django 4.1.7 on 2023-08-01 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0103_alter_familymember_relation_alter_myuser_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranzilaToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('expiry_month', models.CharField(max_length=4)),
                ('expiry_year', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tranzila_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
