# Generated by Django 4.1.7 on 2023-08-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0105_tranziladetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tranzilatoken',
            old_name='expiry_month',
            new_name='expire_month',
        ),
        migrations.RenameField(
            model_name='tranzilatoken',
            old_name='expiry_year',
            new_name='expire_year',
        ),
    ]
