# Generated by Django 4.1.7 on 2023-08-02 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0106_rename_expiry_month_tranzilatoken_expire_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tranziladetail',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='tranziladetail',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='tranziladetail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tranziladetail',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='tranziladetail',
            name='locations_to_activate',
        ),
        migrations.RemoveField(
            model_name='tranziladetail',
            name='plan_to_activate',
        ),
        migrations.RemoveField(
            model_name='tranziladetail',
            name='status',
        ),
        migrations.CreateModel(
            name='StripeDetailNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=200)),
                ('payment_method', models.TextField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('cancellation_reason', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_detail_new', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('plan', 'Plan'), ('deal', 'Deal')], default='plan', max_length=20)),
                ('locations_to_activate', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_to_activate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.plan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_payment_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
