# Generated by Django 4.1.7 on 2023-08-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0107_remove_tranziladetail_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripedetailnew',
            name='payment_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_payment_detail', to='account.paymentdetail'),
        ),
        migrations.AddField(
            model_name='tranziladetail',
            name='payment_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tranzila_payment_detail', to='account.paymentdetail'),
        ),
    ]
