# Generated by Django 4.1.7 on 2023-08-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0109_delete_tranziladetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='sign_svg',
            field=models.TextField(null=True),
        ),
    ]
