# Generated by Django 4.1.7 on 2023-08-03 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0110_currency_sign_svg'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranzilaDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('processor_response_code', models.IntegerField()),
                ('transaction_id', models.IntegerField()),
                ('currency_code', models.CharField(max_length=2)),
                ('expiry_month', models.CharField(max_length=4)),
                ('expiry_year', models.CharField(max_length=4)),
                ('payment_plan', models.CharField(max_length=4)),
                ('credit_card_owner_id', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('card_last_four', models.CharField(max_length=4)),
                ('card_mask', models.CharField(max_length=30)),
                ('card_locality', models.CharField(max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('txn_type', models.CharField(max_length=10)),
                ('tranmode', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tranzila_payment_detail', to='account.paymentdetail')),
            ],
        ),
    ]
