# Generated by Django 4.1.7 on 2023-08-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0111_tranziladetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='pinned_classified',
        ),
    ]
