# Generated by Django 4.1.7 on 2023-08-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0112_remove_myuser_pinned_classified'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranziladetail',
            name='error_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tranziladetail',
            name='error_info',
            field=models.TextField(null=True),
        ),
    ]
