# Generated by Django 4.1.7 on 2023-08-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0114_alter_tranziladetail_card_last_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranziladetail',
            name='transaction_id',
            field=models.IntegerField(null=True),
        ),
    ]
