# Generated by Django 4.1.7 on 2023-08-07 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0116_reviewmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_reviews', to='account.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flaggers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
