# Generated by Django 4.1.7 on 2023-08-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0117_reviewflag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewflag',
            old_name='comment',
            new_name='reason',
        ),
    ]
