# Generated by Django 4.1.7 on 2023-08-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0118_rename_comment_reviewflag_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
