# Generated by Django 4.1.7 on 2023-08-10 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0119_myuser_is_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranzilatoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranzila_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
