# Generated by Django 4.1.7 on 2023-08-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0120_alter_tranzilatoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripedetailnew',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stripedetailnew',
            name='currency',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
