# Generated by Django 4.1.7 on 2023-08-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0122_tranzilatoken_card_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='delete_reason',
            field=models.CharField(choices=[('expectation_not_meet', "Didn't meet expectations "), ('handling_issue', 'Too difficult to navigate, download, upload'), ('expensive', 'Too expensive '), ('choices_issue', 'Not enough choices'), ('not_say', 'Rather Not Say')], max_length=50, null=True),
        ),
    ]
