# Generated by Django 4.1.7 on 2023-08-22 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0123_myuser_delete_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Sub Category Name')),
                ('business_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_sub_categories', to='account.businesscategory')),
            ],
            options={
                'verbose_name': 'sub_category',
                'verbose_name_plural': 'sub_categories',
            },
        ),
    ]
