# Generated by Django 4.1.7 on 2023-08-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0124_businesssubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('user_type', models.CharField(choices=[('member', 'Member'), ('business', 'Business'), ('ngo', 'NGO'), ('news_agency', 'News Agency')], max_length=20)),
            ],
            options={
                'verbose_name': 'user_type_category',
                'verbose_name_plural': 'user_type_categories',
            },
        ),
    ]
