# Generated by Django 4.1.7 on 2023-08-22 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0125_usertypecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_type_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.usertypecategory'),
        ),
    ]
