# Generated by Django 4.1.7 on 2023-08-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0126_myuser_user_type_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='business_sub_category',
            field=models.ManyToManyField(related_name='business_sub_categories', to='account.businesssubcategory'),
        ),
    ]
