# Generated by Django 4.1.7 on 2023-08-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0127_myuser_business_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='business_sub_category',
        ),
    ]
