# Generated by Django 4.1.7 on 2023-08-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0037_remove_deal_business_sub_category'),
        ('account', '0128_remove_myuser_business_sub_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessSubCategory',
        ),
    ]
