# Generated by Django 4.1.7 on 2023-08-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0130_businesscategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='display_type',
            field=models.CharField(default='dropdown', max_length=20),
        ),
    ]
