# Generated by Django 4.1.7 on 2023-08-25 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0131_businesscategory_display_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='stripe',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='StripeDetail',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
