# Generated by Django 4.1.7 on 2023-09-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0133_myuser_extra_weekly_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='provider_type',
            field=models.CharField(choices=[('independent', 'Independent'), ('company', 'Company')], max_length=16, null=True),
        ),
    ]
