# Generated by Django 4.1.7 on 2023-09-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0134_myuser_provider_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='provider_type',
            new_name='service_provider_type',
        ),
    ]
