# Generated by Django 4.1.7 on 2023-09-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0136_myuser_reservation_walkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
