# Generated by Django 4.1.7 on 2023-09-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0137_myuser_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='item_type',
            field=models.CharField(choices=[('plan', 'Plan'), ('deal', 'Deal'), ('weekly_deal', 'Weekly Deal'), ('location', 'Location'), ('classified', 'Classified')], default='plan', max_length=20),
        ),
    ]
