# Generated by Django 4.1.7 on 2023-09-06 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0138_alter_paymentdetail_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGOPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_amount_in_usd', models.FloatField()),
                ('amount', models.FloatField()),
                ('payout', models.BooleanField(default=False)),
                ('payout_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_ngos', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paying_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
