# Generated by Django 4.1.7 on 2023-09-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0139_ngopayout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngopayout',
            name='main_amount_in_usd',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='main_amount_in_usd',
            field=models.FloatField(default=0.0),
        ),
    ]
