# Generated by Django 4.1.7 on 2023-09-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0140_remove_ngopayout_main_amount_in_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngopayout',
            name='payout_date',
            field=models.DateTimeField(null=True),
        ),
    ]
