# Generated by Django 4.1.7 on 2023-09-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0141_alter_ngopayout_payout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngopayout',
            name='payment_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ngo_payment_detail', to='account.paymentdetail'),
        ),
    ]
