# Generated by Django 4.1.7 on 2023-09-11 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0143_vendor_vendorexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorexpense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
