# Generated by Django 4.1.7 on 2023-09-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0144_vendorexpense_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorexpense',
            old_name='Vendor',
            new_name='vendor',
        ),
    ]
