# Generated by Django 4.1.7 on 2023-09-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0145_rename_vendor_vendorexpense_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='facebook_url',
            field=models.TextField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='instagram_url',
            field=models.TextField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='twitter_url',
            field=models.TextField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='website_url',
            field=models.TextField(blank=True, null=True, verbose_name='Website Url'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='youtube_url',
            field=models.TextField(blank=True, null=True, verbose_name='Youtube'),
        ),
    ]
