# Generated by Django 4.1.7 on 2023-09-12 12:50

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0146_alter_myuser_facebook_url_alter_myuser_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypartner',
            name='image',
            field=models.ImageField(max_length=256, null=True, upload_to=account.models.delivery_partners_path),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='image',
            field=models.ImageField(default='default_images/default_profile_pic.jpeg', max_length=256, upload_to=account.models.family_member_pic, verbose_name='Member Pic'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='cover_pic',
            field=models.ImageField(default='default_images/default_cover_pic.png', max_length=256, upload_to=account.models.profile_cover_pic_path, verbose_name='Cover Picture'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='default_images/default_profile_pic.jpeg', max_length=256, upload_to=account.models.profile_pic_path, verbose_name='Profile Pic'),
        ),
    ]
