# Generated by Django 4.1.7 on 2023-09-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0149_alter_onelineuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngovideo',
            name='users_liked',
        ),
    ]
