# Generated by Django 4.1.7 on 2023-09-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0150_remove_ngovideo_users_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorexpense',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vendorexpense',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vendorexpense',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
