# Generated by Django 4.1.7 on 2023-09-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0151_vendorexpense_amount_vendorexpense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorexpense',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
