# Generated by Django 4.1.7 on 2023-09-22 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0152_vendorexpense_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_payment_detail', to='account.paymentdetail')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_paying_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
