# Generated by Django 4.1.7 on 2023-09-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0153_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranziladetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
