# Generated by Django 4.1.7 on 2023-10-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0155_tranziladetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='plan_upgrade_date',
            field=models.DateField(null=True),
        ),
    ]
