# Generated by Django 4.1.7 on 2023-10-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0157_userlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
    ]
