# Generated by Django 4.1.7 on 2023-10-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0158_remove_location_is_primary_remove_location_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='store_manager_email',
            field=models.EmailField(max_length=256, null=True, verbose_name='Store Managed Email Address'),
        ),
        migrations.AddField(
            model_name='location',
            name='store_manager_phone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Store Managed Phone Number'),
        ),
    ]
