# Generated by Django 4.1.7 on 2023-10-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0160_alter_location_store_manager_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='store_manager_email',
            field=models.EmailField(max_length=256, verbose_name='Store Managed Email Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='store_manager_phone',
            field=models.CharField(max_length=17, verbose_name='Store Managed Phone Number'),
        ),
    ]
