# Generated by Django 4.1.7 on 2023-10-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0162_alter_location_store_manager_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_store',
            field=models.BooleanField(default=True),
        ),
    ]
