# Generated by Django 4.1.7 on 2023-10-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0163_myuser_is_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_store',
        ),
    ]
