# Generated by Django 4.1.7 on 2023-10-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0164_remove_myuser_is_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_store',
            field=models.BooleanField(default=False),
        ),
    ]
