# Generated by Django 4.1.7 on 2023-10-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0165_myuser_is_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripedetailnew',
            name='card_mask',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stripedetailnew',
            name='expire_month',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='stripedetailnew',
            name='expire_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
