# Generated by Django 4.1.7 on 2023-11-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0167_alter_plan_amount_alter_plan_donation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='donation',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='shuk_tv',
        ),
    ]
