# Generated by Django 4.1.7 on 2024-01-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0169_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_default_ngo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('member', 'Member'), ('business', 'Business'), ('ngo', 'Non Profitable Organization'), ('news_agency', 'News Agency')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='user_type',
            field=models.CharField(choices=[('member', 'Member'), ('business', 'Business'), ('ngo', 'Non Profitable Organization'), ('news_agency', 'News Agency')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usertypecategory',
            name='user_type',
            field=models.CharField(choices=[('member', 'Member'), ('business', 'Business'), ('ngo', 'Non Profitable Organization'), ('news_agency', 'News Agency')], max_length=20),
        ),
    ]
