# Generated by Django 4.1.7 on 2024-02-19 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0170_myuser_is_default_ngo_alter_myuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='item_type',
            field=models.CharField(choices=[('plan', 'Plan'), ('deal', 'Deal'), ('weekly_deal', 'Weekly Deal'), ('location', 'Location'), ('classified', 'Classified'), ('new_payment_method', 'New Payment Method')], default='plan', max_length=20),
        ),
        migrations.CreateModel(
            name='StripePaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.TextField(null=True)),
                ('card_mask', models.CharField(max_length=30, null=True)),
                ('expire_month', models.CharField(max_length=4, null=True)),
                ('expire_year', models.CharField(max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
