# Generated by Django 4.1.7 on 2024-02-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0171_alter_paymentdetail_item_type_stripepaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepaymentmethod',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tranzilatoken',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
