# Generated by Django 4.1.7 on 2024-03-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0173_businesscategory_name_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='name_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='name_he',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='name_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
