# Generated by Django 4.1.7 on 2024-03-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0174_businesscategory_name_ar_businesscategory_name_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertypecategory',
            name='name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usertypecategory',
            name='name_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usertypecategory',
            name='name_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usertypecategory',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usertypecategory',
            name='name_he',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usertypecategory',
            name='name_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usertypecategory',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
