# Generated by Django 4.1.7 on 2024-03-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0175_usertypecategory_name_ar_usertypecategory_name_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='delete_reason',
            field=models.CharField(choices=[('expectation_not_meet', "Didn't meet expectations"), ('handling_issue', 'Too difficult to navigate, download, upload'), ('expensive', 'Too expensive'), ('choices_issue', 'Not enough choices'), ('not_say', 'Rather Not Say')], max_length=50, null=True),
        ),
    ]
