# Generated by Django 4.1.7 on 2024-04-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0176_alter_myuser_delete_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripedetailnew',
            name='event_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
