INSERT INTO `account_businesscategory` (`id`, `name`, `keyword`, `parent_id`, `display_type`, `name_es`, `name_ar`, `name_de`, `name_fr`, `name_he`, `name_pt`, `name_ru`) VALUES
(1, 'Product', 'product', NULL, 'dropdown', 'Producto', 'منتج', 'Produkt', 'produit', 'מוצר', 'produto', 'продукт'),
(2, 'Service', 'service', NULL, 'dropdown', 'servicio', 'خدمة', 'Dienstleistung', 'service', 'שירות', 'serviço', 'услуга'),
(3, 'Restaurant', 'restaurant', NULL, 'dropdown', 'restaurante', 'مطعم', 'Restaurant', 'restaurant', 'מסעדה', 'restaurante', 'ресторан'),
(4, 'Travel', 'travel', NULL, 'dropdown', 'viajar', 'سفر', 'reisen', 'voyager', 'לטוס', 'viajar', 'путешествовать'),
(5, 'Real Estate', 'real_estate', NULL, 'dropdown', 'bienes', 'العقارات', 'Immobilien', 'immobilier', 'נדל\"ן', 'imóveis', 'недвижимость'),
(6, 'Entertainment/Sports', 'entertainment_sport', NULL, 'dropdown', 'Entretenimiento/Deportes', 'ترفيه/رياضة', 'Unterhaltung/Sport\n', 'Divertissement/Sports', 'בידור/ספורט', 'Entretenimento/Esportes', 'Развлечения/Спорт'),
(10, 'Rent', 'rent', 5, 'radio', 'alquiler', 'إيجار', 'Miete', 'loyer', 'שכירות', 'aluguel', 'аренда'),
(11, 'Vacation Rentals', 'vacation_rental', 5, 'radio', 'Alquileres de vacaciones', 'إيجارات العطلات', 'Ferienwohnungen', 'Locations de vacances', 'השכרת חופש', 'Aluguel de temporada', 'Аренда на каникулах'),
(12, 'Sale', 'sale', 5, 'radio', 'venta', 'بيع', 'Verkauf', 'vente', 'מכירה', 'venda', 'продажа'),
(13, 'Venue', 'venue', 6, 'radio', 'lugar', 'مكان', 'Veranstaltungsort', 'lieu', 'מקום', 'local', 'место'),
(14, 'Sports', 'sport', 6, 'radio', 'deportes', 'رياضة', 'Sport', 'sports', 'ספורט', 'esportes', 'спорт'),
(15, 'Movie Theaters', 'movie_theater', 6, 'radio', 'cines', 'دور السينما', 'Kinos', 'cinémas', 'בתי קולנוע', 'cinemas', 'кинотеатры'),
(16, 'Vehicles /Transportation', NULL, 1, 'dropdown', 'Vehículos/Transporte', ' مركبات/نقل ', 'Fahrzeuge/Transport', 'Véhicules/Transport', ' רכבים/תחבורה', 'Veículos/Transporte', ' Транспорт/Транспортировка'),
(17, 'Roommate / Room Share', NULL, 1, 'dropdown', 'compañero de cuarto / compartición de habitación', 'زميل سكن / مشاركة غرفة ', 'Mitbewohner / Zimmer teilen', 'colocataire / colocation', 'חבר דירה / שיתוף חדר', 'colega de quarto / compartilhamento de quarto', 'сосед по комнате / совместное жилье'),
(18, 'Clothing', NULL, 1, 'dropdown', 'Ropa', ' ملابس', 'Kleidung', 'Vêtements', ' בגדים ', 'Roupas', 'Одежда'),
(19, 'Furniture', NULL, 1, 'dropdown', 'Muebles', 'أثاث', 'Möbel', 'Meubles', 'רהיטים', 'Móveis', 'Мебель'),
(20, 'Electronics', NULL, 1, 'dropdown', 'Electrónica', 'إلكترونيات', 'Elektronik', 'Électronique', 'אלקטרוניקה', 'Eletrônicos', 'Электроника'),
(21, 'Antiques & Collectibles', NULL, 1, 'dropdown', 'Antigüedades y Coleccionables', 'تحف وتحفيظات ', 'Antiquitäten und Sammlerstücke', 'Antiquités et Objets de Collection', 'יוקרתיים ואוספים ', 'Antiguidades e Colecionáveis', 'Антиквариат и Коллекционирование'),
(22, 'Appliances', NULL, 1, 'dropdown', 'Electrodomésticos', 'أجهزة كهربائية ', 'Haushaltsgeräte', 'Appareils électroménagers', ' מכשירי חשמל', 'Eletrodomésticos', 'Бытовая техника'),
(23, 'Books, Films & Music', NULL, 1, 'dropdown', 'Libros, Películas y Música', ' كتب، أفلام وموسيقى', 'Bücher, Filme und Musik', 'Livres, Films et Musique', 'ספרים, סרטים ומוזיקה', 'Livros, Filmes e Música', 'Книги, Фильмы и Музыка'),
(24, 'Tools', NULL, 1, 'dropdown', 'Herramientas', ' أدوات', 'Werkzeuge', 'Outils', 'כלים', 'Ferramentas', 'Инструменты'),
(25, 'FREE', NULL, 1, 'dropdown', 'GRATIS', 'مجاناً', 'KOSTENLOS', 'GRATUIT', 'חינם', 'GRÁTIS', 'БЕСПЛАТНО'),
(26, 'Heath & Beauty', NULL, 1, 'dropdown', 'Salud y Belleza', 'الصحة والجمال ', 'Gesundheit und Schönheit', 'Santé et Beauté', 'בריאות ויופי ', 'Saúde e Beleza', 'Здоровье и Красота'),
(27, 'Jewellery & Watches', NULL, 1, 'dropdown', 'Joyas y Relojes', 'مجوهرات وساعات ', 'Schmuck und Uhren', 'Bijoux et Montres', 'תכשיטים ושעונים', 'Joias e Relógios', 'Ювелирные изделия и Часы'),
(28, 'Home Goods & Decor', NULL, 1, 'dropdown', 'Artículos para el hogar y Decoración', 'سلع منزلية وديكور ', 'Haushaltswaren und Dekor', 'Articles ménagers et Décoration', ' מוצרי בית וקישוטים', 'Artigos para Casa e Decoração', 'Товары для дома и Декор'),
(29, 'Luggage & Bags', NULL, 1, 'dropdown', 'Equipaje y bolsos', 'أمتعة و حقائب', 'Gepäck und Taschen', 'Valises et sacs', 'מזוודות ותיקים', 'Bagagem e bolsas', 'Багаж и сумки'),
(30, 'Musical Instruments', NULL, 1, 'dropdown', 'Instrumentos musicales', 'الات موسيقية', 'Musikinstrumente', 'Instruments de musique', 'כלי נגינה', 'Instrumentos musicais', 'Музыкальные инструменты'),
(31, 'Patio & Garden', NULL, 1, 'dropdown', 'Patio y jardín', 'الفناء والحديقة', 'Terrasse & Garten', 'Patio et jardin', 'פטיו וגן', 'Pátio e jardim', 'Патио и сад'),
(32, 'Pets & Supplies', NULL, 1, 'dropdown', 'Mascotas y suministros', 'الحيوانات الأليفة والمستلزمات', 'Haustiere & Vorräte', 'Animaux et fournitures', 'חיות מחמד ואספקה', 'Animais de estimação e suprimentos', 'Домашние животные и расходные материалы'),
(33, 'Sporting Goods', NULL, 1, 'dropdown', 'Artículos deportivos', 'بضائع رياضيه', 'Sportwaren', 'Articles de sport', 'מוצרי ספורט', 'Artigos esportivos', 'Спортивные товары'),
(34, 'Toys & Games', NULL, 1, 'dropdown', 'Juguetes y Juegos', 'الألعاب والألعاب', 'Spielzeug & Spiele', 'Jouets et jeux', 'צעצועים ומשחקים', 'Brinquedos e jogos', 'Игрушки и игры'),
(35, 'Automotive', NULL, 2, 'dropdown', 'Automotor', 'السيارات', 'Automobil', 'Automobile', 'רכב', 'Automotivo', 'Автомобиль'),
(36, 'Beauty', NULL, 2, 'dropdown', 'Belleza', 'جمال', 'Schönheit', 'Beauté', 'יוֹפִי', 'Beleza', 'Красота'),
(37, 'Cell / Mobile', NULL, 2, 'dropdown', 'Celda / móvil', 'الخلية / الهاتف المحمول', 'Zelle / Mobile', 'Cellule / mobile', 'תא / נייד', 'Célula / celular', 'Ячейка / мобильный'),
(38, 'Computer', NULL, 2, 'dropdown', 'Computadora', 'حاسوب', 'Computer', 'Ordinateur', 'מַחשֵׁב', 'Computador', 'Компьютер'),
(39, 'Cycle', NULL, 2, 'dropdown', 'Ciclo', 'دورة', 'Zyklus', 'Faire du vélo', 'מחזור', 'Ciclo', 'Цикл'),
(40, 'Event Planing', NULL, 2, 'dropdown', 'Planificación de eventos', 'تخطيط الأحداث', 'Ereignisplanung', 'Planage de l\'événement', 'תכנון אירועים', 'Planejamento de eventos', 'Планирование событий'),
(41, 'Garden/ Landscaping', NULL, 2, 'dropdown', 'Jardín/ paisajismo', 'الحديقة/ المناظر الطبيعية', 'Garten/ Landschaftsbau', 'Jardin / aménagement paysager', 'גן/ גינון', 'Jardim/ paisagismo', 'Сад/ ландшафт'),
(42, 'Financial', NULL, 2, 'dropdown', 'Financiero', 'مالي', 'Finanziell', 'Financier', 'כַּספִּי', 'Financeiro', 'Финансовый'),
(43, 'Health / Wellness', NULL, 2, 'dropdown', 'Salud y bienestar', 'الصحة والعافية', 'Gesundheit', 'Santé', 'בריאות / בריאות', 'Saúde e bem estar', 'Здоровье / здоровье'),
(44, 'Household / Cleaning', NULL, 2, 'dropdown', 'Limpieza doméstica', 'التنظيف المنزلية', 'Haushaltsreinigung', 'Nettoyage ménager', 'משק בית / ניקוי', 'Doméstico / limpeza', 'Домохозяйство / уборка'),
(45, 'Labor / Moving l Hauling', NULL, 2, 'dropdown', 'Trabajo / mudanza l de transporte', 'العمل / الحركة', 'Arbeit / bewegt l Transport', 'Travail / déménagement en transport en l', 'עבודה / העברה L הובלה', 'Trabalho / Motivo para transportar', 'Труд / Перемещение L перевозки'),
(46, 'Legal', NULL, 2, 'dropdown', 'Legal', 'قانوني', 'Legal', 'Légal', 'משפטי', 'Jurídico', 'Юридический'),
(47, 'Lessons & Tutoring', NULL, 2, 'dropdown', 'Lecciones y tutoría', 'الدروس والدروس', 'Lektionen & Nachhilfe', 'Leçons et tutorat', 'שיעורים וחליפות', 'Lições e aulas', 'Уроки и репетиторство'),
(48, 'Pet', NULL, 2, 'dropdown', 'Mascota', 'حيوان أليف', 'Haustier', 'Animal de compagnie', 'חיית מחמד', 'Bicho de estimação', 'Домашний питомец'),
(49, 'Real Estate', NULL, 2, 'dropdown', 'Bienes raíces', 'العقارات', 'Immobilie', 'Immobilier', 'נדל\"ן', 'Imobiliária', 'Недвижимость'),
(50, 'Skilled Trade', NULL, 2, 'dropdown', 'Comercio especializado', 'التجارة الماهرة', 'Fachhandel', 'Métier qualifié', 'מסחר מיומן', 'Comércio qualificado', 'Квалифицированная торговля'),
(51, 'Travel/Vacation', NULL, 2, 'dropdown', 'Viajes/vacaciones', 'السفر/الإجازة', 'Reisen/Urlaub', 'Voyage / vacances', 'נסיעות/חופשה', 'Viagens/férias', 'Путешествие/Отпуск'),
(52, 'Entertaiment / Artists and Production', NULL, 2, 'dropdown', 'Entretaimente / artistas y producción', 'entertaiment / الفنانين والإنتاج', 'Entertaiment / Künstler und Produktion', 'Enterrent / artistes et production', 'Entertaiment / אמנים והפקה', 'ENTERTERAIMENT / ARTISTAS E PRODUÇÃO', 'Entertaiment / Artists и производство'),
(53, 'Fast Food', NULL, 3, 'dropdown', 'Comida rápida', 'الطعام السريع', 'Fastfood', 'Fast food', 'אוכל מהיר', 'Comida rápida', 'Быстрое питание'),
(54, 'Delivery Only', NULL, 3, 'dropdown', 'Solo entrega', 'التسليم فقط', 'Lieferverkehr frei', 'Livraison uniquement', 'משלוח בלבד', 'Apenas entrega', 'Только доставка'),
(55, 'Asian', NULL, 3, 'dropdown', 'asiático', 'آسيوي', 'asiatisch', 'asiatique', 'אסייתי', 'Asiático', 'Азиатский'),
(56, 'Italian', NULL, 3, 'dropdown', 'italiano', 'إيطالي', 'Italienisch', 'italien', 'אִיטַלְקִית', 'italiano', 'Итальянский'),
(57, 'Mexican', NULL, 3, 'dropdown', 'mexicano', 'مكسيكي', 'Mexikaner', 'mexicain', 'מֶקסִיקָני', 'mexicano', 'Мексиканец'),
(58, 'Indian', NULL, 3, 'dropdown', 'indio', 'هندي', 'indisch', 'Indien', 'הוֹדִי', 'indiano', 'Индийский'),
(59, 'Middle Eastern', NULL, 3, 'dropdown', 'Medio este', 'شرق اوسطي', 'Nahen Osten', 'Moyen-Orient', 'מזרח תיכוני', 'Oriente médio', 'Ближневосточный'),
(60, 'Deli', NULL, 3, 'dropdown', 'fiambres', 'أطعمة لذيذة', 'Delikatessen', 'épicerie fine', 'מעדניה', 'Delicatessen', 'гастроном'),
(61, 'Desserts', NULL, 3, 'dropdown', 'Postres', 'الحلويات', 'Nachspeisen', 'Desserts', 'קינוחים', 'Sobremesas', 'Десерты'),
(62, 'Kosher', NULL, 3, 'dropdown', 'Comestible según la ley judía', 'كوشير', 'Koscher', 'Kascher', 'כשר', 'Kosher', 'Кошер'),
(63, 'Burger', NULL, 3, 'dropdown', 'Hamburguesa', 'برغر', 'Burger', 'Burger', 'בורגר', 'Hambúrguer', 'Бургер'),
(64, 'Vegetarian / Vegan', NULL, 3, 'dropdown', 'Vegetariano / vegano', 'نباتي / نباتي', 'Vegetarier / vegan', 'Végétarien / végétalien', 'צמחוני / טבעוני', 'Vegetariano / vegano', 'Вегетарианский / веганский'),
(65, 'Kid Friendly', NULL, 3, 'dropdown', 'Amigable para niños', 'ودية للأطفال', 'Kinderfreundlich', 'Accueille les enfants', 'ידידותי לילדים', 'Amigável para crianças', 'Малыш'),
(66, 'Mediterranean', NULL, 3, 'dropdown', 'Mediterráneo', 'البحر المتوسط', 'Mittelmeer', 'méditerranéen', 'יָם תִיכוֹנִי', 'Mediterrâneo', 'Средиземноморье'),
(67, 'Family Style', NULL, 3, 'dropdown', 'Estilo familiar', 'نمط الأسرة', 'Familienstil', 'Style familial', 'סגנון משפחתי', 'Estilo familiar', 'Семейный стиль'),
(68, 'Fish / Seafood', NULL, 3, 'dropdown', 'Pescado / mariscos', 'الأسماك / المأكولات البحرية', 'Fisch / Meeresfrüchte', 'Poisson / fruits de mer', 'דגים / פירות ים', 'Peixe / frutos do mar', 'Рыба / морепродукты'),
(69, 'Steak house', NULL, 3, 'dropdown', 'Asador', 'بيت شرائح اللحم', 'Steak-House', 'Steak House', 'סטייקיה', 'Churrascaria', 'Стейк-хаус'),
(70, 'French', NULL, 3, 'dropdown', 'Francés', 'فرنسي', 'Französisch', 'Français', 'צָרְפָתִית', 'Francês', 'Французский'),
(71, 'Ethnic Cooking', NULL, 3, 'dropdown', 'Cocina étnica', 'الطبخ العرقي', 'Ethnische Küche', 'Cuisine ethnique', 'בישול אתני', 'Culinária étnica', 'Этническая кулинария'),
(72, 'Airline', NULL, 4, 'dropdown', 'Aerolínea', 'شركة طيران', 'Fluggesellschaft', 'Compagnie aérienne', 'חֶברַת תְעוּפָה', 'CIA aérea', 'Авиакомпания'),
(73, 'Hotel', NULL, 4, 'dropdown', 'Hotel', 'الفندق', 'Hotel', 'Hôtel', 'מלון', 'Hotel', 'Гостиница'),
(74, 'Bed & Breakfast', NULL, 4, 'dropdown', 'Cama y Desayuno', 'سرير و فطور', 'Bed & Breakfast', 'lit et petit-déjeuner', 'שינה וארוחת בוקר', 'Bed & Breakfast', 'Кровать и завтрак'),
(75, 'Motel', NULL, 4, 'dropdown', 'Motel', 'فندق صغير', 'Motel', 'Motel', 'מוֹטֶל', 'Motel', 'Мотель'),
(76, 'Hostel', NULL, 4, 'dropdown', 'Albergue', 'نزل', 'Herberge', 'Auberge', 'הוסטל', 'Hostel', 'Общежитие'),
(77, 'Camping', NULL, 4, 'dropdown', 'Cámping', 'تخييم', 'Camping', 'Camping', 'קֶמפִּינג', 'Acampamento', 'Кемпинг'),
(78, 'Car Rental', NULL, 4, 'dropdown', 'Alquiler de coches', 'تاجير سيارة', 'Autovermietung', 'Location de voiture', 'השכרת רכב', 'Aluguel de carros', 'Прокат автомобилей'),
(79, 'Park and Recreation', NULL, 4, 'dropdown', 'Parque y recreación', 'الحديقة والترفيه', 'Park und Erholung', 'Parc et loisirs', 'פארק ובילוי', 'Parque e recreação', 'Парк и отдых'),
(80, 'Amusement Park', NULL, 4, 'dropdown', 'Parque de atracciones', 'حديقة الملاهي', 'Freizeitpark', 'Parc d\'attractions', 'פארק השעשועים', 'Parque de diversões', 'Парк с аттракционами'),
(81, 'Shopping', NULL, 4, 'dropdown', 'Compras', 'التسوق', 'Einkaufen', 'Achats', 'קניות', 'Compras', 'Покупка'),
(82, 'Tours', NULL, 4, 'dropdown', 'Excursiones', 'جولات', 'Touren', 'Tournées', 'סיורים', 'Passeios', 'Туры'),
(83, 'Transportation Rentals', NULL, 4, 'dropdown', 'Alquiler de transporte', 'إيجارات النقل', 'Transportvermietungen', 'Location de transport', 'השכרת הובלה', 'Aluguel de transporte', 'Транспортная аренда'),
(84, 'Apartments / Housing', NULL, 10, 'dropdown', 'Apartamentos / vivienda', 'الشقق / السكن', 'Wohnungen / Wohnungen', 'Appartements / logements', 'דירות / דיור', 'Apartamentos / moradia', 'Квартиры / Жилье'),
(85, 'Sublet / Temporary', NULL, 10, 'dropdown', 'Subarriendo / temporal', 'Sublet / مؤقت', 'Untervermietung / vorübergehend', 'Sous-location / temporaire', 'תת -סובל / זמני', 'Subblina / temporária', 'Сублет / временный'),
(86, 'Office & Commercial', NULL, 10, 'dropdown', 'Oficina y comercial', 'المكتب والتجاري', 'Büro & kommerziell', 'Bureau et publicité', 'משרד ומסחר', 'Escritório e Comercial', 'Офис и коммерческий'),
(87, 'Apartments / Housing', NULL, 12, '', 'Apartamentos / vivienda', 'الشقق / السكن', 'Wohnungen / Wohnungen', 'Appartements / logements', 'דירות / דיור', 'Apartamentos / moradia', 'Квартиры / Жилье'),
(88, 'Office & Commercial', NULL, 12, '', 'Oficina y comercial', 'المكتب والتجاري', 'Büro & kommerziell', 'Bureau et publicité', 'משרד ומסחר', 'Escritório e Comercial', 'Офис и коммерческий'),
(89, 'Amusement Park', NULL, 13, 'dropdown', 'Parque de atracciones', 'حديقة الملاهي', 'Freizeitpark', 'Parc d\'attractions', 'פארק השעשועים', 'Parque de diversões', 'Парк с аттракционами'),
(90, 'Amusement Park', NULL, 13, 'dropdown', 'Parque de atracciones', 'حديقة الملاهي', 'Freizeitpark', 'Parc d\'attractions', 'פארק השעשועים', 'Parque de diversões', 'Парк с аттракционами'),
(91, 'Casinos', NULL, 13, 'dropdown', 'Casinos', 'الكازينوهات', 'Casinos', 'Casinos', 'בתי קזינו', 'Cassinos', 'Казино'),
(92, 'Concert Halls', NULL, 13, 'dropdown', 'Salas de conciertos', 'قاعات الحفلات الموسيقية', 'Konzerthallen', 'Salles de concert', 'אולמות קונצרטים', 'Salas de concertos', 'Концертные залы'),
(93, 'Live Music', NULL, 13, 'dropdown', 'Música en vivo', 'موسيقى مباشره', 'Live Musik', 'Musique live', 'מוסיקת חיה', 'Música ao vivo', 'Живая музыка'),
(94, 'Nightclubs/Bar', NULL, 13, 'dropdown', 'Clubes nocturnos/bar', 'النوادي الليلية/البار', 'Nachtclubs/Bar', 'Clubs de nuit / bar', 'מועדוני לילה/בר', 'Boates/bar', 'Ночные клубы/бар'),
(95, 'Theater', NULL, 13, 'dropdown', 'Teatro', 'مسرح', 'Theater', 'Théâtre', 'תיאטרון', 'Teatro', 'Театр'),
(96, 'Cultural Center', NULL, 13, 'dropdown', 'Centro Cultural', 'مركز ثقافي', 'Kulturzentrum', 'Centre culturel', 'מרכז תרבות', 'Centro Cultural', 'Культурный центр'),
(97, 'Community Center', NULL, 13, 'dropdown', 'Centro Comunitario', 'مركز اجتماعي', 'Gemeindezentrum', 'Centre communautaire', 'מרכז קהילתי', 'Centro Comunitário', 'Общественный центр'),
(98, 'Parks', NULL, 13, 'dropdown', 'Parque', 'الحدائق', 'Parks', 'Parcs', 'פארקים', 'Parques', 'Парки'),
(99, 'American Football', NULL, 14, 'dropdown', 'fútbol americano', 'كرة القدم الأمريكية', 'Amerikanischer Fußball', 'football américain', 'כדורגל אמריקאי', 'futebol americano', 'американский футбол'),
(100, 'Basketball', NULL, 14, 'dropdown', 'Baloncesto', 'كرة سلة', 'Basketball', 'Basket-ball', 'כדורסל', 'Basquetebol', 'Баскетбол'),
(101, 'Soccer', NULL, 14, 'dropdown', 'Fútbol', 'كرة القدم', 'Fußball', 'Football', 'כדורגל', 'Futebol', 'Футбольный'),
(102, 'Cricket', NULL, 14, 'dropdown', 'Grillo', 'كريكيت', 'Kricket', 'Criquet', 'קרִיקֶט', 'Grilo', 'Крикет'),
(103, 'Baseball', NULL, 14, 'dropdown', 'Béisbol', 'البيسبول', 'Baseball', 'Base-ball', 'בייסבול', 'Beisebol', 'Бейсбол'),
(104, 'Ice Hockey', NULL, 14, 'dropdown', 'Hockey sobre hielo', 'الهوكى الجليدى', 'Eishockey', 'Hockey sur glace', 'הוקי קרח', 'Hockey no gelo', 'Хоккей'),
(105, 'Tennis', NULL, 14, 'dropdown', 'Tenis', 'تنس', 'Tennis', 'Tennis', 'טֶנִיס', 'tênis', 'Большой теннис'),
(106, 'Motorsports', NULL, 14, 'dropdown', 'Portavoz', 'رياضة السيارات', 'Motorsport', 'Sport automobile', 'מוטורספורט', 'Motorsports', 'Автоспорта'),
(107, 'Marathons', NULL, 14, 'dropdown', 'Maratones', 'ماراثون', 'Marathons', 'Marathons', 'מרתונים', 'Maratonas', 'Марафоны'),
(108, 'Cycling', NULL, 14, 'dropdown', 'Ciclismo', 'ركوب الدراجات', 'Radfahren', 'Vélo', 'רכיבה על אופניים', 'Ciclismo', 'Езда на велосипеде'),
(109, 'Maccabiah', NULL, 14, 'dropdown', 'Maccabiah', 'مكابيا', 'MACCABIAH', 'Maccabia', 'מכביה', 'Maccabiah', 'Маккабия'),
(110, 'Olympics', NULL, 14, 'dropdown', 'Juegos Olímpicos', 'الألعاب الأولمبية', 'Olympia', 'Jeux olympiques', 'אולימפיאדה', 'Olimpíadas', 'Олимпийские игры'),
(111, 'Action', NULL, 15, 'dropdown', 'Acción', 'فعل', 'Aktion', 'Action', 'פעולה', 'Ação', 'Действие'),
(112, 'Horror', NULL, 15, 'dropdown', 'Horror', 'رعب', 'Grusel', 'Horreur', 'חֲרָדָה', 'Horror', 'Ужастик'),
(113, 'Drama', NULL, 15, 'dropdown', 'Drama', 'دراما', 'Theater', 'Drame', 'דְרָמָה', 'Drama', 'Драма'),
(114, 'Comedy', NULL, 15, 'dropdown', 'Comedia', 'كوميديا', 'Komödie', 'Comédie', 'קוֹמֶדִיָה', 'Comédia', 'Комедия'),
(115, 'Western', NULL, 15, 'dropdown', 'occidental', 'الغربي', 'Western', 'Occidental', 'מערבי', 'Ocidental', 'Западный'),
(116, 'Documentary', NULL, 15, 'dropdown', 'Documental', 'وثائقي', 'Dokumentarfilm', 'Documentaire', 'דוקומנטרי', 'Documentário', 'Документальный'),
(117, 'Romance', NULL, 15, 'dropdown', 'Romance', 'رومانسي', 'Romantik', 'Romance', 'רומנטיקה', 'Romance', 'Роман'),
(118, 'Thriller', NULL, 15, 'dropdown', 'Suspenso', 'إثارة', 'Thriller', 'Thriller', 'מוֹתְחָן', 'Filme de ação', 'Триллер'),
(119, 'SciFy', NULL, 15, 'dropdown', 'Chiflado', 'تفكيك', 'Surfen', 'Glissant', 'ציקי', 'Scify', 'Scify'),
(120, 'Kids', NULL, 15, 'dropdown', 'Niños', 'أطفال', 'Kinder', 'Enfants', 'ילדים', 'Crianças', 'Дети'),
(121, 'Independent', NULL, 15, 'dropdown', 'Independiente', 'مستقل', 'Unabhängig', 'Indépendant', 'עצמאי', 'Independente', 'Независимый'),
(122, 'Musical', NULL, 15, 'dropdown', 'Musical', 'موسيقي', 'Musical', 'Musical', 'מוּסִיקָלִי', 'Musical', 'Мюзикл');
