# Generated by Django 4.1.7 on 2023-05-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('payment_pending', 'Payment Pending')], default='active', max_length=20),
        ),
    ]
