# Generated by Django 4.1.7 on 2023-05-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_application_email_application_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
    ]
