# Generated by Django 4.1.7 on 2023-05-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_application_email_alter_application_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='reuse',
            field=models.BooleanField(default=True),
        ),
    ]
