# Generated by Django 4.1.7 on 2023-05-24 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_application_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobclick',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_clicks', to='jobs.job'),
        ),
    ]
