# Generated by Django 4.1.7 on 2023-05-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_jobclick_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
