# Generated by Django 4.1.7 on 2023-05-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_application_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=20, verbose_name='Job Type'),
        ),
    ]
