# Generated by Django 4.1.7 on 2023-07-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='Salary Type'),
        ),
    ]
