# Generated by Django 4.1.7 on 2023-07-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_salary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payment_currency',
            field=models.CharField(choices=[('usd', 'Dollar'), ('eur', 'Euro'), ('gbp', 'British Pound'), ('ils', 'Israeli Shekels'), ('aud', 'Australian Dollar')], default='usd', max_length=5),
        ),
    ]
