# Generated by Django 4.1.7 on 2023-07-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_job_payment_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='payment_currency',
            new_name='salary_currency',
        ),
    ]
