# Generated by Django 4.1.7 on 2023-04-03 10:06

import deals.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('actual_price', models.FloatField(verbose_name='Actual Price')),
                ('deal_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('online_offline', 'Online Offline')], default='online', max_length=20, verbose_name='Deal Type')),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage Off')], default='fixed', max_length=20, verbose_name='Discount Type')),
                ('discount_value', models.FloatField(verbose_name='Off Value')),
                ('code', models.CharField(max_length=20, verbose_name='Coupon/Deal Code')),
                ('weekly', models.BooleanField(default=False, verbose_name='Weekly Deal')),
                ('duration', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.deal')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(blank=True, choices=[('type1', 'Type1'), ('type2', 'Type2')], max_length=24, null=True)),
                ('rental_type', models.CharField(blank=True, choices=[('sale', 'Sale'), ('rent', 'Rent'), ('vacation_rental', 'Vacation Rental')], max_length=24, null=True)),
                ('offer_text', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('property_location', models.TextField(blank=True, null=True, verbose_name='Property Location')),
                ('property_location_latitude', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('property_location_longitude', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=30, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='Country')),
                ('zipcode', models.IntegerField(blank=True, null=True, verbose_name='Zipcode')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Phone Number')),
                ('email', models.IntegerField(blank=True, null=True, verbose_name='Email')),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_detail', to='deals.deal')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.order')),
            ],
        ),
        migrations.CreateModel(
            name='DealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=deals.models.deal_images)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.deal')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('image', models.ImageField(upload_to='', verbose_name='Category Image')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
