# Generated by Django 4.1.7 on 2023-04-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
