# Generated by Django 4.1.7 on 2023-04-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_alter_deal_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='discount_type',
            new_name='club_member_discount_type',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='discount_value',
            new_name='club_member_discount_value',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='code',
        ),
        migrations.AddField(
            model_name='deal',
            name='club_member_code',
            field=models.CharField(default='', max_length=20, verbose_name='Coupon/Deal Code'),
        ),
        migrations.AddField(
            model_name='deal',
            name='free_member_code',
            field=models.CharField(default=0, max_length=20, verbose_name='Coupon/Deal Code'),
        ),
        migrations.AddField(
            model_name='deal',
            name='free_member_discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage Off')], default='fixed', max_length=20, verbose_name='Discount Type'),
        ),
        migrations.AddField(
            model_name='deal',
            name='free_member_discount_value',
            field=models.FloatField(default=0, verbose_name='Off Value'),
        ),
    ]
