# Generated by Django 4.1.7 on 2023-04-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_rename_discount_type_deal_club_member_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='club_member_code',
            field=models.CharField(max_length=20, verbose_name='Coupon/Deal Code'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='free_member_code',
            field=models.CharField(max_length=20, verbose_name='Coupon/Deal Code'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='free_member_discount_value',
            field=models.FloatField(verbose_name='Off Value'),
        ),
    ]
