# Generated by Django 4.1.7 on 2023-04-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_deal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='duration',
        ),
        migrations.AlterField(
            model_name='deal',
            name='club_member_code',
            field=models.CharField(max_length=20, null=True, verbose_name='Coupon/Deal Code'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='club_member_discount_value',
            field=models.FloatField(null=True, verbose_name='Off Value'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
