# Generated by Django 4.1.7 on 2023-04-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_remove_deal_duration_alter_deal_club_member_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='club_member_discount_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage Off')], default='', max_length=20, null=True, verbose_name='Discount Type'),
        ),
    ]
