# Generated by Django 4.1.7 on 2023-04-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_alter_deal_club_member_discount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='city',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='property_location',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='property_location_latitude',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='property_location_longitude',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='state',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='deal',
            name='actual_price',
            field=models.FloatField(default=0, verbose_name='Actual Price'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='free_member_code',
            field=models.CharField(max_length=20, null=True, verbose_name='Coupon/Deal Code'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='free_member_discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage Off')], max_length=20, null=True, verbose_name='Discount Type'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='free_member_discount_value',
            field=models.FloatField(null=True, verbose_name='Off Value'),
        ),
    ]
