# Generated by Django 4.1.7 on 2023-04-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_remove_propertydetails_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyDetails',
        ),
    ]
