# Generated by Django 4.1.7 on 2023-04-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0015_propertydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='phone',
            field=models.CharField(max_length=17, verbose_name='Phone Number'),
        ),
    ]
