# Generated by Django 4.1.7 on 2023-04-19 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0017_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealimage',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_images', to='deals.deal'),
        ),
    ]
