# Generated by Django 4.1.7 on 2023-04-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0018_alter_dealimage_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
