# Generated by Django 4.1.7 on 2023-05-23 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0019_deal_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealRedeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='redeemed_deals', to='deals.deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='redeemed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
