# Generated by Django 4.1.7 on 2023-07-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0020_dealredeem'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='price_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=24),
        ),
    ]
