# Generated by Django 4.1.7 on 2023-07-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0021_propertydetails_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='price_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=24, null=True),
        ),
    ]
