# Generated by Django 4.1.7 on 2023-07-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0022_alter_propertydetails_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='offer_text',
            field=models.TextField(null=True),
        ),
    ]
