# Generated by Django 4.1.7 on 2023-07-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0023_alter_propertydetails_offer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='phone',
            field=models.CharField(max_length=17, null=True, verbose_name='Phone Number'),
        ),
    ]
