# Generated by Django 4.1.7 on 2023-07-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0028_alter_deal_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
