# Generated by Django 4.1.7 on 2023-07-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0030_remove_deal_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
