# Generated by Django 4.1.7 on 2023-08-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0034_dealclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
