# Generated by Django 4.1.7 on 2023-08-22 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0127_myuser_business_sub_category'),
        ('deals', '0035_deal_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='business_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category_deals', to='account.businesssubcategory'),
        ),
    ]
