# Generated by Django 4.1.7 on 2023-08-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0036_deal_business_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='business_sub_category',
        ),
    ]
