# Generated by Django 4.1.7 on 2023-08-23 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0131_businesscategory_display_type'),
        ('deals', '0037_remove_deal_business_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='business_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category_deals', to='account.businesscategory'),
        ),
        migrations.AddField(
            model_name='deal',
            name='business_sub_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_sub_category_deals', to='account.businesscategory'),
        ),
    ]
