# Generated by Django 4.1.7 on 2023-08-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0038_deal_business_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydetails',
            name='rental_type',
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('hotel', 'Hotel'), ('guest_house', 'Guest House'), ('hostel_pg', 'Hostel/PG'), ('farmhouse', 'Farmhouse'), ('houseboat', 'Houseboat')], max_length=24),
        ),
    ]
