# Generated by Django 4.1.7 on 2023-08-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0039_remove_propertydetails_rental_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='no_of_bathroom',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='no_of_bedroom',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='sq_feet',
            field=models.IntegerField(null=True),
        ),
    ]
