# Generated by Django 4.1.7 on 2023-08-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0040_propertydetails_no_of_bathroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
