# Generated by Django 4.1.7 on 2023-08-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0041_alter_propertydetails_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='number_of_travellers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='property_class',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
