# Generated by Django 4.1.7 on 2023-09-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0042_deal_number_of_travellers_deal_property_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='property_class',
            field=models.CharField(choices=[('1', '1 Star'), ('2', '2 Star'), ('3', '3 Star'), ('4', '4 Star'), ('5', '5 Star')], max_length=100, null=True),
        ),
    ]
