# Generated by Django 4.1.7 on 2023-09-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0043_alter_deal_property_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='rent_period',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
