# Generated by Django 4.1.7 on 2023-09-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0044_propertydetails_rent_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='ngo_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='deal',
            name='shuk_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
