# Generated by Django 4.1.7 on 2023-09-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0045_deal_ngo_fee_deal_shuk_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
