# Generated by Django 4.1.7 on 2023-09-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0047_deal_online_supported'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='redemption_link',
            field=models.TextField(null=True),
        ),
    ]
