# Generated by Django 4.1.7 on 2023-10-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0048_deal_redemption_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='all_stores',
            field=models.BooleanField(default=False),
        ),
    ]
