# Generated by Django 4.1.7 on 2023-05-30 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_news_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
