# Generated by Django 4.1.7 on 2023-05-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('payment_pending', 'Payment Pending')], default='active', max_length=20),
        ),
    ]
