# Generated by Django 4.1.7 on 2023-05-30 07:22

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_news_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to=article.models.news_pic_path),
        ),
    ]
