# Generated by Django 4.1.7 on 2023-05-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='delete_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
