# Generated by Django 4.1.7 on 2023-05-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_news_delete_requested_news_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('draft', 'Draft'), ('published', 'Published')], default='pending', max_length=20),
        ),
    ]
