# Generated by Django 4.1.7 on 2023-06-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
