"""shuktv URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from account.api import api_views as account_views
from classifieds.api import api_views as classified_views
from deals.api import api_views as deal_views
from jobs.api import api_views as job_views
from content.api import api_views as content_views
from article.api import api_views as article_views
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
]

urlpatterns += i18n_patterns(path(
    '', include('account.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
urlpatterns += i18n_patterns(
    path('api/v1/account/register/',
        account_views.RegisterView.as_view(), name='register'),
    path('api/v1/account/otp_verify/',
         account_views.OTPVerifyView.as_view(), name='otp_verify'),
    path('api/v1/account/registration-send-otp-on-phone/',
         account_views.RegistrationPhoneOTPSendView.as_view(), name='registration_send_otp_on_phone'),
    path('api/v1/account/registration-verify-otp-phone/',
         account_views.RegistrationPhoneOTPVerifyView.as_view(), name='registration_verify_otp_phone'),
    path('api/v1/account/send-otp-on-phone/',
         account_views.PhoneOTPSendView.as_view(), name='send_otp_on_phone'),
    path('api/v1/account/verify-otp-phone/',
         account_views.PhoneOTPVerifyView.as_view(), name='verify_otp_phone'),
    path('api/v1/account/login/', account_views.LoginView.as_view(), name='login'),
    path('api/v1/account/token/refresh/',
         account_views.TokenRefreshAPIView.as_view(), name='token_refresh'),
    path('api/v1/account/logout/', account_views.LogoutView.as_view()),
    path('api/v1/account/authenticate-password/', account_views.AuthenticatePasswordView.as_view(), name='login'),
    path('api/v1/account/get-access-from-temptoken/',
          account_views.GetAccessFromTempToken.as_view(), name='get-access-from-temptoken'),
    path('api/v1/account/get-basicinfo-from-temptoken/',
          account_views.GetBasicInfoFromTempToken.as_view(), name='get-info-from-temptoken'),
    path('api/v1/account/forgot-password/',
         account_views.ForgotPasswordAPIView.as_view(), name='forgot-password'),
    path('api/v1/account/resend-otp/',
         account_views.ResendOtpAPIView.as_view(), name='resend-otp'),
    path('api/v1/account/resend-otp-email-update/',
         account_views.ResendOtpEmailUpdateAPIView.as_view(), name='resend-otp-email-update'),
    path('api/v1/account/verify-code/',
         account_views.CodeVerificationAPIView.as_view(), name="verify-code"),
    path('api/v1/account/new-password/',
        account_views.NewPasswordAPIView.as_view(), name="new-password"),
    path('api/v1/account/update-password/',
         account_views.UpdatePasswordAPIView.as_view(), name="update-password"),
    path('api/v1/account/update-profile/',
         account_views.UpdateProfileView.as_view(), name="update-profile"),
    path('api/v1/account/relations/',
         account_views.RelationsListView.as_view(), name="relations-listing"),
    path('api/v1/account/add-update-family-member/',
         account_views.FamilyMemberView.as_view(), name="add-update-family-member"),
    path('api/v1/account/delete-reasons/',
          account_views.DeleteAccountReasonView.as_view(), name='delete-account-reasons'),
    path('api/v1/account/delete-self-account/',
          account_views.DeleteAccountView.as_view(), name='delete-account'),
    path('api/v1/account/delete-family-member/',
         account_views.DeleteFamilyMemberView.as_view(), name="delete-family-member"),
    path('api/v1/account/ngos/',
         account_views.NgoListView.as_view(), name="ngos-listing"),
    path('api/v1/account/countries/',
         account_views.CountryListView.as_view(), name="countries-listing"),
    path('api/v1/account/languages/',
         account_views.LanguageListView.as_view(), name="languages-listing"),
    path('api/v1/account/currencies/',
         account_views.CurrencyListView.as_view(), name="currencies-listing"),
    path('api/v1/account/plans/',
         account_views.PlanListView.as_view(), name="plans-listing"),
    path('api/v1/account/plan/activate-new',
         account_views.PlanActivateNewView.as_view(), name="plan-activate-new"),
    path('api/v1/account/categories/',
         account_views.CategoriesListView.as_view(), name='categories_list'),
    path('api/v1/account/sub-categories/<int:category_id>',
         account_views.SubCategoriesListView.as_view(), name='sub_categories_list'),
    path('api/v1/account/update-profile',
         account_views.UpdateProfileView.as_view(), name="update-profile"),
    path('api/v1/account/profile-details',
         account_views.ProfileDetailsView.as_view(), name="profile-details"),
    path('api/v1/account/other-profile-details/<int:user_id>',
         account_views.OtherProfileDetailsView.as_view(), name="other-profile-details"),
    path('api/v1/account/add-locations',
         account_views.LocationAddView.as_view(), name="add_locations"),
    path('api/v1/account/update-location/<int:location_id>',
         account_views.LocationUpdateView.as_view(), name="update_location"),
#     path('api/v1/account/check-locations',
#          account_views.LocationCheckView.as_view(), name="check_locations"),
    path('api/v1/account/add-locations-payment',
         account_views.LocationPaymentView.as_view(), name="add_location_payment"),
    path('api/v1/account/locations',
         account_views.LocationListView.as_view(), name="locations"),
    path('api/v1/account/delete-location/<int:location_id>',
         account_views.DeleteLocationView.as_view(), name="delete-location"),
    path('api/v1/account/delivery-partners',
         account_views.DeliveryPartnerListView.as_view(), name="delivery-partners"),
    path('api/v1/account/add-ngo-video',
         account_views.NgoVideoCreateView.as_view(), name="add-ngo-video"),
    path('api/v1/account/ngo-videos',
         account_views.NgoVideoListView.as_view(), name="ngo-videos"),
    path('api/v1/account/ngo-video-detail/<int:ngo_video_id>',
         account_views.NgoVideoDetailView.as_view(), name="ngo-video-detail"),
    path('api/v1/account/update-ngo-video/<int:ngo_video_id>',
         account_views.UpdateNgoVideoView.as_view(), name="update-ngo-video"),
    path('api/v1/account/delete-ngo-video/<int:ngo_video_id>',
         account_views.DeleteNgoVideoView.as_view(), name="delete-ngo-video"),
    path('api/v1/account/new-email-address',
         account_views.NewEmailAddressView.as_view(), name="new-email-address"),
    path('api/v1/account/change-email-address',
         account_views.ChangeEmailAddressView.as_view(), name="change-email-address"),
    path('api/v1/account/subscribe-news-letter',
         account_views.SubscribeNewsletter.as_view(), name="subscribe-news-letter"),
    path('api/v1/account/add-remove-favourite-user/<int:user_id>',
         account_views.AddRemoveFavouriteUserView.as_view(), name="add-remove-favourite-user"),
    path('api/v1/account/like-unlike-ngo-video/<int:video_id>',
         account_views.LikeUnlikeNgoVideoView.as_view(), name="like-unlike-ngo-video"),
    path('api/v1/account/add-review',
         account_views.AddUserReviewView.as_view(), name="add-review"),
    path('api/v1/account/user/reviews/<int:user_id>',
         account_views.UserReviewListView.as_view(), name="user-reviews"),
    path('api/v1/account/review/mark-useful',
         account_views.UserReviewMarkUsefulView.as_view(), name="mark-user-reviews"),
    path('api/v1/account/review/flag',
         account_views.UserReviewAddFlagView.as_view(), name="flag-review"),
    path('api/v1/account/ngo-partners/',
         account_views.NgoPartnersListView.as_view(), name="ngos-partners"),
    path('api/v1/account/business-profiles/',
         account_views.BusinessProfileListView.as_view(), name="business-profiles"),
    path('api/v1/account/member-users/',
         account_views.MemberUserListView.as_view(), name="member-users"),
    path('api/v1/account/add-remove-favourite-video/<int:video_id>',
         account_views.AddRemoveFavouriteNgoVideoView.as_view(), name="add-remove-favourite-video"),
    path('api/v1/account/all-favourite-wishlist/<str:type>',
         account_views.AllFavoiriteWishlist.as_view(), name="all-favourite-wishlist"),
    path('api/v1/account/popular-media-houses',
         account_views.PopularNewsAgencyListView.as_view(), name="popular-media-houses"),
    path('api/v1/account/unit-product-cost',
         account_views.UnitProductCostListView.as_view(), name="unit_product_cost"),
    path('api/v1/account/flag-user',
         account_views.AddUserFlagView.as_view(), name="flag_user"),
    path('api/v1/account/user-type-categories/<str:user_type>',
         account_views.UserTypeCategoryView.as_view(), name="user_type_categories"),
    path('api/v1/account/my-payment-history',
         account_views.PaymentHistoryView.as_view(), name="my_payment_history"),
    path('api/v1/account/download-payment-invoice/<int:payment_id>',
         account_views.PaymentInvoiceDownloadView.as_view(), name="payment_invoice_download"),
    path('api/v1/account/ngo-payment-history',
         account_views.NGOPaymentHistoryView.as_view(), name="ngo_payment_history"),
    path('api/v1/account/ngo-payment-report',
         account_views.NGOPaymentReportView.as_view(), name="ngo_payment_report"),
    path('api/v1/account/update-ngo',
         account_views.UpdateNGOView.as_view(), name="update_ngo"),
)


urlpatterns += i18n_patterns(
    path('api/v1/classified-categories',
         classified_views.ClassifiedCategoryView.as_view(), name="classified-categories"),
    path('api/v1/classified/add',
         classified_views.CreateClassifiedView.as_view(), name="add-classified"),
    path('api/v1/classified/update/<int:classified_id>',
         classified_views.UpdateClassifiedView.as_view(), name="update-classified"),
    path('api/v1/my-classifieds',
         classified_views.MyClassifiedListView.as_view(), name="list-classified"),
    path('api/v1/others-classifieds',
         classified_views.OthersClassifiedListView.as_view(), name="list-classified"),
    path('api/v1/classified/delete/<int:classified_id>',
         classified_views.DeleteClassifiedView.as_view(), name="delete-classified"),
    path('api/v1/classified/detail/<int:classified_id>',
         classified_views.ClassifiedDetailView.as_view(), name="classified-detail"),
    path('api/v1/classified/add-remove-favourite-classified/<int:classified_id>',
         classified_views.AddRemoveFavouriteClassifiedView.as_view(), name="add-remove-favourite-classified"),
    path('api/v1/user-classifieds/<int:user_id>',
         classified_views.UserClassifiedListView.as_view(), name="user-classifieds"),
    path('api/v1/user-pinned-classified/<int:user_id>',
         classified_views.UserPinnedClassifiedView.as_view(), name="user-classifieds"),
    path('api/v1/classified/flag-classified',
         classified_views.AddClassifiedFlagView.as_view(), name="flag_classified"),
)

urlpatterns += i18n_patterns(
    path('api/v1/business-deal/add',
         deal_views.CreateBusinessDealView.as_view(), name="add-business-deal"),
    path('api/v1/property-types',
         deal_views.PropertyTypesListView.as_view(), name="property-types"),
    path('api/v1/property-deal/add',
         deal_views.CreatePropertyDealView.as_view(), name="add-property-deal"),
    path('api/v1/property-deal/update/<int:deal_id>',
         deal_views.UpdatePropertyDealView.as_view(), name="update-property-deal"),
    path('api/v1/deals',
         deal_views.DealListView.as_view(), name="list-deal"),
    path('api/v1/deal/update/<int:deal_id>',
         deal_views.UpdateDealView.as_view(), name="update-deal"),
    path('api/v1/deal/detail/<int:deal_id>',
          deal_views.DealDetailView.as_view(), name="deal-detail"),
    path('api/v1/deal/delete/<int:deal_id>',
         deal_views.DeleteDealView.as_view(), name="delete-deal"),
    path('api/v1/deal/others-weekly-deals',
         deal_views.OthersWeeklyDealsListView.as_view(), name="others-weekly-deals"),
    path('api/v1/deal/my-weekly-deals',
         deal_views.MyWeeklyDealsListView.as_view(), name="my-weekly-deals"),
    path('api/v1/user-deals/<int:user_id>',
         deal_views.UserDealListView.as_view(), name="user-deals"),
    path('api/v1/deal/add-review',
         deal_views.AddDealReviewView.as_view(), name="add-review"),
    path('api/v1/deal/reviews/<int:deal_id>',
         deal_views.DealReviewListView.as_view(), name="deal-reviews"),
    path('api/v1/deal/review/mark-useful',
         deal_views.DealReviewMarkUsefulView.as_view(), name="mark-deal-reviews"),
    path('api/v1/deal/review/flag',
         deal_views.DealReviewAddFlagView.as_view(), name="flag-deal-review"),
    path('api/v1/deal/recommended-deals',
         deal_views.RecommendedDealsView.as_view(), name="recommended-deals"),
    path('api/v1/deal/ngo-deals',
         deal_views.NgoDealListView.as_view(), name="ngo-deals"),
    path('api/v1/deal/ngo-weekly-deals',
         deal_views.NgoWeeklyDealListView.as_view(), name="ngo-weekly-deals"),
    path('api/v1/deal/user-recommended-deals/<int:user_id>',
         deal_views.UserRecommendedDealsView.as_view(), name="user-recommended-deals"),
    path('api/v1/deal/business-category-deals/<str:business_category>',
         deal_views.BusinessCategoryDealsView.as_view(), name="business-category-deals"),
    path('api/v1/deal/real-estate-deals/<str:business_sub_category>',
         deal_views.RealEstateDealsView.as_view(), name="real-estate-deals"),
    path('api/v1/deal/all-business-deals/',
         deal_views.AllBusinessCategoryDealsView.as_view(), name="all-business-category-deals"),
    path('api/v1/deal/all-real-estate-deals',
         deal_views.AllRealEstateDealsView.as_view(), name="all-real-estate-deals"),
    path('api/v1/deal/add-remove-favourite-deal/<int:deal_id>',
         deal_views.AddRemoveFavouriteDealView.as_view(), name="add-remove-favourite-deal"),
    path('api/v1/deal/redeem/<int:deal_id>',
         deal_views.RedeemDealView.as_view(), name="redeem-deal"),
    path('api/v1/deal/redeemers/<int:deal_id>',
         deal_views.DealRedeemersView.as_view(), name="deal-redeemeds"),
    path('api/v1/deal/my-redeemed-deals',
         deal_views.RedeemedDealslist.as_view(), name="my-redeemed-deals"),
    path('api/v1/deal/flag-deal',
         deal_views.AddDealFlagView.as_view(), name="flag_deal"),

)

urlpatterns += i18n_patterns(
    path('api/v1/job/add',
         job_views.CreateJobView.as_view(), name="add-job"),
    path('api/v1/all-jobs',
         job_views.AllJobsListView.as_view(), name="all-jobs"),
    path('api/v1/recent-jobs',
         job_views.RecentJobListView.as_view(), name="recent-jobs"),
    path('api/v1/past-jobs',
         job_views.PastJobListView.as_view(), name="past-jobs"),
    path('api/v1/job/update/<int:job_id>',
         job_views.UpdateJobView.as_view(), name="update-job"),
    path('api/v1/job/detail/<int:job_id>',
         job_views.JobDetailView.as_view(), name="job-detail"),
    path('api/v1/job/delete/<int:job_id>',
         job_views.DeleteJobView.as_view(), name="job-delete"),
    path('api/v1/job/resume-list',
         job_views.ResumeListView.as_view(), name="resume-list"),
    path('api/v1/job/apply',
         job_views.ApplyJobView.as_view(), name="job-apply"),
    path('api/v1/job/statistics/<int:job_id>',
         job_views.JobStatisticsView.as_view(), name="job-statistics"),
    path('api/v1/job/applicants/<int:job_id>',
         job_views.JobApplicantsView.as_view(), name="job-applicants"),
    path('api/v1/job/delete-application',
         job_views.DeleteJobApplicantView.as_view(), name="delete-job-application"),
    path('api/v1/deal/add-remove-favourite-job/<int:job_id>',
         job_views.AddRemoveFavouriteJobView.as_view(), name="add-remove-favourite-job"),
)


urlpatterns += i18n_patterns(
    path('api/v1/faqs',
         content_views.FaqListView.as_view(), name="faqs"),
    path('api/v1/about-us',
         content_views.AboutUsView.as_view(), name="about-us"),
    path('api/v1/contact-us',
         content_views.ContactUsView.as_view(), name="contact-us"),
    path('api/v1/terms-and-conditions',
         content_views.TermsAndConditionsView.as_view(), name="terms-and-conditions"),
    path('api/v1/privacy-policy',
         content_views.PrivacyPolicyView.as_view(), name="privacy-policy"),
)

urlpatterns += i18n_patterns(
    path('api/v1/news/add',
         article_views.CreateNewsView.as_view(), name="add-news"),
    path('api/v1/others-news',
         article_views.OthersNewsListView.as_view(), name="others-news"),
    path('api/v1/my-news',
         article_views.MyNewsListView.as_view(), name="my-news"),
    path('api/v1/news/update/<int:news_id>',
         article_views.UpdateNewsView.as_view(), name="update-news"),
    path('api/v1/news/detail/<int:news_id>',
         article_views.NewsDetailView.as_view(), name="news-detail"),
    path('api/v1/news/delete/<int:news_id>',
         article_views.DeleteNewsView.as_view(), name="news-delete"),
    path('process-stripe-payment', account_views.StripeWebhookNewView.as_view(), name='process_stripe_payment'),
    path('generate-stripe-intent', account_views.GenerateStripeIntentView.as_view(), name='generate_stripe_intent'),
    path('process-stripe-payment-new', account_views.StripeWebhookNewView.as_view(), name='process_stripe_payment_new'),
    path('process-tranzila-payment', account_views.TranzilaPaymentView.as_view(), name='process_tranzila_payment'),
    path('add-new-tranzila-payment-method', account_views.AddTranzilaPaymentMethodView.as_view(), name='add_new_tranzila_payment'),
    path('markdefault-tranzila-payment-method/<int:payment_method_id>', account_views.MarkDefaultTranzilaPaymentMethodView.as_view(), name='markdefault_tranzila_payment'),
    path('delete-tranzila-payment-method/<int:payment_method_id>', account_views.DeleteTranzilaPaymentMethodView.as_view(), name='delete_tranzila_payment'),
    path('get-tranzila-token', account_views.GetTranzilaTokenView.as_view(), name='get_tranzila_token'),
    path('get-stripe-payment-methods', account_views.GetStripePaymentMethodView.as_view(), name='get_stripe_payment_methods'),
    path('process-stripe-saved', account_views.StripePaymentView.as_view(), name='process_stripe_saved'),

    path('list-stripe-payment-methods', account_views.ListStripePaymentMethodView.as_view(), name='list_stripe_payment_methods'),
    path('create-stripe-checkout-session', account_views.CreateCheckoutSessionView.as_view(), name='create_stripe_checkout_session'),
    path('add-stripe-payment-method', account_views.AddStripePaymentMethodView.as_view(), name='add_stripe_payment_method'),
    path('markdefault-stripe-payment-method', account_views.MarkDefaultStripePaymentMethodView.as_view(), name='markdefault_stripe_payment_method'),
    path('delete-stripe-payment-method', account_views.DeleteStripePaymentMethodView.as_view(), name='delete_stripe_payment_method'),
    path('get-stripe-payment-status/<int:payment_detail>', account_views.PaymentDetailStatusView.as_view(), name='get_stripe_payment_status'),
)

urlpatterns += i18n_patterns(
    path('api/v1/master-search-params',
         deal_views.MasterSearchParamView.as_view(), name="master-search-params"),
    path('api/v1/master-search',
         deal_views.MasterSearchView.as_view(), name="master-search"),
)