# Generated by Django 4.1.7 on 2023-04-13 04:45

import classifieds.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0043_ngoreferaltoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('monthly_price', models.FloatField(verbose_name='Monthly Price')),
                ('contact_phone', models.IntegerField(blank=True, null=True, verbose_name='Contact Phone')),
                ('contact_email', models.IntegerField(blank=True, null=True, verbose_name='Contact Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassifiedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=classifieds.models.classified_images)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.classified')),
            ],
        ),
    ]
