# Generated by Django 4.1.7 on 2023-04-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0002_alter_classified_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='contact_phone',
            field=models.EmailField(blank=True, max_length=17, null=True, verbose_name='Contact Phone'),
        ),
    ]
