# Generated by Django 4.1.7 on 2023-04-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_alter_classified_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Contact Phone'),
        ),
    ]
