# Generated by Django 4.1.7 on 2023-04-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0006_alter_classified_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
