# Generated by Django 4.1.7 on 2023-04-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0007_alter_classified_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classified',
            old_name='monthly_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='classified',
            name='price_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
