# Generated by Django 4.1.7 on 2023-04-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0008_rename_monthly_price_classified_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='price_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
