# Generated by Django 4.1.7 on 2023-04-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0010_classified_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedimage',
            name='classified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_images', to='classifieds.classified'),
        ),
    ]
