# Generated by Django 4.1.7 on 2023-07-19 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0092_alter_currency_sign'),
        ('classifieds', '0011_alter_classifiedimage_classified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_classified', to='account.location'),
        ),
    ]
