# Generated by Django 4.1.7 on 2023-07-20 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifieds', '0012_alter_classified_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flagged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_flags', to='classifieds.classified')),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_flaggers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
