# Generated by Django 4.1.7 on 2023-08-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0013_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
