# Generated by Django 4.1.7 on 2023-08-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0015_classified_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
