# Generated by Django 4.1.7 on 2023-08-24 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0016_classifiedcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifieds.classifiedcategory'),
        ),
    ]
