# Generated by Django 4.1.7 on 2023-08-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0017_classified_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='product_condition',
            field=models.CharField(choices=[('new', 'New'), ('old', 'Old')], default='new', max_length=3),
        ),
    ]
