# Generated by Django 4.1.7 on 2023-09-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0018_classified_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='ngo_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='classified',
            name='shuk_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='classified',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
