# Generated by Django 4.1.7 on 2023-09-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0019_classified_ngo_fee_classified_shuk_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
