# Generated by Django 4.1.7 on 2023-09-08 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifieds', '0020_classified_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_clicks', to='classifieds.classified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_clickers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
