# Generated by Django 4.1.7 on 2023-09-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0021_classifiedclick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifiedclick',
            old_name='deal',
            new_name='classified',
        ),
    ]
