# Generated by Django 4.1.7 on 2024-03-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0022_rename_deal_classifiedclick_classified'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedcategory',
            name='name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classifiedcategory',
            name='name_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classifiedcategory',
            name='name_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classifiedcategory',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classifiedcategory',
            name='name_he',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classifiedcategory',
            name='name_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classifiedcategory',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
