# Generated by Django 4.1.7 on 2023-08-16 09:27

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_termsandcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to=content.models.aboutus_pictures_path)),
                ('counter', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=content.models.aboutus_pictures_path)),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('facebook_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('linkedin_link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='heading',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='sub_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='sub_heading',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
