# Generated by Django 4.1.7 on 2023-08-16 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_aboutjourney_aboutteam_about_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutjourney',
            name='about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_journeys', to='content.about'),
        ),
        migrations.AddField(
            model_name='aboutteam',
            name='about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_teams', to='content.about'),
        ),
    ]
