# Generated by Django 4.1.7 on 2023-08-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_aboutjourney_about_aboutteam_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutjourney',
            name='about',
        ),
        migrations.RemoveField(
            model_name='aboutteam',
            name='about',
        ),
    ]
