# Generated by Django 4.1.7 on 2024-03-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_aboutjourney_icon_alter_aboutteam_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
