# Generated by Django 4.1.7 on 2024-03-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_privacypolicy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandcondition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
