# Generated by Django 4.1.7 on 2024-06-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_termsandcondition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
